[sdk]
target = "qemux86_64"
release = "apollo/edge"
version = "0.1.0"
metadata-path = "_avocado/metadata" # default
repos-path = "_avocado/repos" #default
image = "avocadolinux/sdk:apollo-edge"

[package]
name = "my-system"
version = "0.1.0"
description = "My System"
build-script = "avocado-system.sh"
workspace-path = "_avocado/workspace"
output-path = "_avocado/output" # default

[deps.workspace]
avocado-pkg-bootfiles = "*"
avocado-pkg-kernel = "*"
avocado-img-pkg-initramfsfs = "*"
avocado-img-pkg-var = "*"
my-extension = { path = "./my-extension_qemux86-64_0.1.0.rpm" }
